name: "Build and push images"
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-push:
    if: github.repository == 'sebatec-eu/devcontainers'
    strategy:
      fail-fast: false
      matrix:
        subFolders:
          - subFolder: hugo
            tags:
              - "latest"
              - "1"
              - "1.1"
              - "1.1.1"
          - subFolder: go
            tags:
              - "latest"
              - "1"
              - "1.0"
              - "1.0.0"
          - subFolder: base
            tags:
              - "latest"
              - "1"
              - "1.0"
              - "1.0.0"
    concurrency:
      group: ${{ github.workflow }}-${{ toJSON(matrix.subFolders) }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get meta information of the current build
        id: "meta"
        run: |
          set -xeu
          IMAGE_REVISION=$(git log -1 --pretty=%H ${{ matrix.subFolders.subFolder }})
          echo "IMAGE_REVISION=$IMAGE_REVISION" >> $GITHUB_OUTPUT

          docker pull ghcr.io/sebatec-eu/${{ matrix.subFolders.subFolder }}-devcontainer:${{ matrix.subFolders.tags[0] }}
          PREV_IMAGE_REVISION=$(docker image inspect ghcr.io/sebatec-eu/${{ matrix.subFolders.subFolder }}-devcontainer:${{ matrix.subFolders.tags[0] }} | jq -r '.[].Config.Labels|."org.opencontainers.image.revision"')
          if [ "$PREV_IMAGE_REVISION" = "$IMAGE_REVISION" ]; then
            echo "RUN_BUILD=false" >> $GITHUB_OUTPUT
          else
            echo "RUN_BUILD=true" >> $GITHUB_OUTPUT
          fi
      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/sebatec-eu/${{ matrix.subFolders.subFolder }}-devcontainer
          push: always
          subFolder: ${{ matrix.subFolders.subFolder }}
          imageTag: ${{ join(matrix.subFolders.tags, ',') }}
        env:
          IMAGE_REVISION: "${{ steps.meta.outputs.IMAGE_REVISION }}"
        if: steps.meta.outputs.RUN_BUILD == 'true'
