name: "Build and push images"
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-push:
    if: github.repository == 'sebatec-eu/devcontainers'
    strategy:
      fail-fast: false
      matrix:
        subFolders:
          - subFolder: hugo
            tags:
              - "latest"
              - "1"
              - "1.0"
              - "1.0.3"
          - subFolder: go
            tags:
              - "latest"
              - "1"
              - "1.0"
              - "1.0.0"
    concurrency:
      group: ${{ github.workflow }}-${{ toJSON(matrix.subFolders) }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/sebatec-eu/${{ matrix.subFolders.subFolder }}-devcontainer
          push: always
          subFolder: ${{ matrix.subFolders.subFolder }}
          imageTag: ${{ join(matrix.subFolders.tags, ',') }}
